---
title: "Fusobacteriales extended checks"
author: "Rebecca Hoyd"
date: "7/20/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(RColorBrewer)
# library(DESeq2)
```

# Load data

```{r }
clin.orien <- read.csv("../data/clinical_ORIEN_curated.csv")
clin.tcga <- read.csv("../data/clinical_TCGA_curated.csv")
cprev <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/combined_prevalence.csv")


loadexprs <- function(){
  exprs <- read.csv("/fs/ess/PAS1695/projects/exorien/data/aggregated-expressions.csv") %>%
    filter(sample %in% clin.orien$RNASeq)
  return(exprs)
}
exprs <- loadexprs()
```


# Fusobacteriales prevalence breakdown

```{r}
fusoprev <- cprev  %>%
  filter(order == "o__Fusobacteriales") %>%
  group_by(sample) %>%
  summarise(Fusobacteriales = sum(prev)) %>%
  mutate(Fusobacteriales = ifelse(Fusobacteriales > 0, 1, 0),
         fuso = ifelse(Fusobacteriales == 1, "Present", "NotPresent"))

clin.fuso <- clin.orien %>%
  mutate(sample = RNASeq) %>%
  left_join(fusoprev)

clin.fuso %>%
  group_by(Fusobacteriales, agestat) %>%
  tally()
```

```{r}
clin.fuso.tcga <- clin.tcga %>%
  mutate(sample = sample.microbe) %>%
  left_join(fusoprev)

clin.fuso.tcga %>%
  group_by(Fusobacteriales, agestat) %>%
  tally()
```

# DESeq2

```{r}
exprs.form <- exprs %>%
  select(-TCGA.code) %>%
  pivot_longer(-sample, names_to = "gene", values_to = "counts") %>%
  mutate(counts = round((2^counts))) %>%
  pivot_wider(names_from = "sample", values_from = "counts") %>%
  column_to_rownames(var = "gene") %>%
  select(clin.fuso$sample)

identical(colnames(exprs.form), clin.fuso$sample)
```


```{r}
dds <- DESeqDataSetFromMatrix(countData = exprs.form, colData = clin.fuso, design = ~ fuso)
dds <- DESeq(dds)

des.res <- results(dds) %>%
  as.data.frame() %>%
  rownames_to_column(var = "gene")

write.csv(des.res, "../data/deseq2_fusobacteriales-expression.csv", row.names = F)
```

# FGSEA

```{r}
library(msigdbr)
library(fgsea) # Doesn't load if DESeq2 is loaded

des.res <- read.csv("../data/deseq2_fusobacteriales-expression.csv", stringsAsFactors = F)
```

```{r prepare hallmark database}
msig.human <- msigdbr(species = "Homo sapiens") %>%
  dplyr::select(gs_cat, entrez_gene, gs_name, gene_symbol, gs_description) %>%
  dplyr::rename("pathname" = gs_name, "genes" = gene_symbol, "desc" = gs_description,
                "category" = gs_cat, "NCBI Entrez ID" = entrez_gene) 

msig.hlmrk <- msig.human %>%
    filter(category=="H") %>%
    unique()

hlmrk.paths <- msig.hlmrk %>%
     dplyr::select(genes, pathname) %>%
     split(x = .$genes, f = .$pathname)

```

```{r perform fgsea and quickly check results}
sig.genes <- des.res %>%
  filter(padj < 0.05)
sig.est <- sig.genes$log2FoldChange
names(sig.est) <- sig.genes$gene

fgsea.res <- fgsea(hlmrk.paths, sig.est)

fgsea.res %>%
  filter(padj < 0.05) %>%
  select(pathway, padj, NES)
```

```{r save fgsea results}
fgsea.res.df <- fgsea.res %>%
  arrange(padj)
fgsea.res.df$leadingEdge <- unlist(lapply(fgsea.res.df$leadingEdge, function(x) paste(x, collapse = ",")))
write.csv(arrange(fgsea.res.df, padj), "../data/fgsea_fuso-prev.csv")
```

# Visualizations

```{r}
des.res <- read.csv("../data/deseq2_fusobacteriales-expression.csv", stringsAsFactors = F)
fgsea.res <- read.csv("../data/fgsea_fuso-prev.csv", stringsAsFactors = F)
```

```{r formatting}
# Fix pathway names
fgsea.sig <- fgsea.res %>%
  filter(padj < 0.05) %>%
  mutate(pathname = str_to_sentence(str_replace_all(str_remove(pathway, "HALLMARK_"), "_", " ")),
         pathname = case_when(pathway == "HALLMARK_TNFA_SIGNALING_VIA_NFKB" ~ "TNFA signaling via NKFB",
                              pathway == "HALLMARK_MTORC1_SIGNALING" ~ "MTORC1 signaling",
                              pathway == "HALLMARK_IL6_JAK_STAT3_SIGNALING" ~ "IL6 JAK STAT3 signaling",
                              !pathway %in% c("HALLMARK_TNFA_SIGNALING_VIA_NFKB",
                                              "HALLMARK_MTORC1_SIGNALING",
                                              "HALLMARK_IL6_JAK_STAT3_SIGNALING") ~ pathname))

# get gene labels
genelab.pathways.tmp <- lapply(fgsea.sig$leadingEdge, function(x) str_split(x,pattern = ",") %>%
                             as.data.frame(col.names = "gene"))
names(genelab.pathways.tmp) <- fgsea.sig$pathname
genelab.pathways <- lapply(fgsea.sig$pathname, function(x) genelab.pathways.tmp[[x]] %>% 
                             mutate(pathname = x)) %>%
  bind_rows() %>%
  add_count(gene) %>%
  mutate(pathlab = ifelse(n > 1, "Multiple pathways", pathname))

# Main data inputs for plots
volcin <- des.res %>%
  left_join(genelab.pathways) %>%
  mutate(alphcode = ifelse(is.na(pathlab), "back", "highlight"),
         n = case_when(n > 1 ~ 3,
                       n == 1 ~ 2,
                       .default = 1)
         # n = replace_na(n,1)
         )

lda.in <- fgsea.sig %>%
  arrange(NES)

# Aesthetics tweaks and harmonizing
path.ord <- lda.in$pathname

getPallete <- colorRampPalette(brewer.pal(11, "Spectral"))
col.harm <- c(getPallete(nrow(lda.in)), "black")
names(col.harm) <- c(path.ord, "Multiple pathways")
col.harm[["IL6 JAK STAT3 signaling"]] <- "yellow"
```


```{r volcano}
volcin %>%
  ggplot(aes(x = log2FoldChange, y = -log(padj), color = pathlab, alpha = alphcode, size = n)) +
  geom_point(shape = 1, show.legend = F) +
  geom_hline(yintercept = -log(0.05), lty = 2) +
  scale_color_manual(values = col.harm, name = "Pathway", na.value = "grey80") +
  scale_alpha_manual(values = c(.2,1)) +
  scale_size_continuous(range = c(1,3)) +
  # guides(alpha = "none",
  #        size = "none") +
  theme_bw() 
  # theme(panel.background = element_rect(fill = "grey80"),
  #       panel.grid = element_line(color = "grey85"))
```

```{r LDA style}
lda.in %>%
  ggplot(aes(x = fct_relevel(pathname, path.ord), y = NES, fill = pathname)) +
  geom_col() +
  scale_fill_manual(breaks = rev(path.ord),values = col.harm, name = "Pathway") +
  labs(x = "", y = "Normalized expression score") +
  coord_flip() +
  theme_bw()
```

