---
title: "Figure 4"
author: "Rebecca Hoyd"
date: "10/17/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggrepel)
```


# Heatmap (Panel A)

```{r}
load("../data/prepared-figure-data/heatmap_corrs.rda")

micim.heat %>%
  mutate(corr.source = str_remove(corr.source, "correlation.")) %>%
  ggplot(aes(x = microbe, y = newlabs, fill = correlation)) +
  facet_grid(corr.source ~ onset) +
  geom_tile() +
  scale_fill_viridis_c(na.value = "white",
                       name = "Correlation",
                       option = "H") +
  labs(x = "Microbe", y = "") +
  theme_bw() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(size =8),
        panel.background = element_rect(fill = "white"),
        panel.grid = element_blank(),
        legend.position = "bottom")

ggsave("../figures/heatmap_TCGA-ORIEN_dropmics.png", height = 6, width = 7.5)
```

# Scatterplots

## Neutrophils (Panel B)
```{r}
load("../data/prepared-figure-data/scatterplot_corrs.rda")

micim.full %>%
    filter(newlabs == "Neutrophils") %>%
    ggplot(aes(x = ORIEN.est, y = TCGA.est, color = sigcode, label = mlab)) +
    facet_wrap(vars(onset), nrow = 2) +
    geom_point() +
    geom_text_repel(show.legend = F) +
    geom_hline(yintercept = 0) +
    geom_vline(xintercept = 0) +
    scale_color_manual(values = c("darkgreen", "black", "orange", "blue"),
                       name = "Significant in") +
    labs(x = "ORIEN correlation", y = "TCGA correlation") +
    theme_bw()
  
  ggsave(filename = "../figures/scatterplots_mic-immune_neutrophil.png", 
         height = 10, width = 20)
    ggsave(filename = "../figures/scatterplots_mic-immune_neutrophil_labels.svg", 
         height = 10, width = 20)
      ggsave(filename = "../figures/scatterplots_mic-immune_neutrophil_in-ms.svg", 
         height = 2, width = 3.75)
```


```{r}
load("../data/prepared-figure-data/scatterplot_corrs.rda")

micim.full %>%
    filter(newlabs == "Neutrophils") %>%
    ggplot(aes(x = ORIEN.est, y = TCGA.est, color = sigcode, label = mlab)) +
    facet_wrap(vars(onset), nrow = 2) +
    geom_point(show.legend = FALSE) +
    geom_text_repel(show.legend = F) +
    geom_hline(yintercept = 0) +
    geom_vline(xintercept = 0) +
    scale_color_manual(values = c("darkgreen", "black", "orange", "blue"),
                       name = "Significant in") +
    labs(x = "ORIEN correlation", y = "TCGA correlation") +
    theme_bw()
    
  ggsave(filename = "../figures/scatterplots_mic-immune_neutrophil_in-ms_no-legend.svg", 
         height = 4, width = 3.5)
```
## Mast cells (Panel C)

```{r}
load("../data/prepared-figure-data/scatterplot_corrs.rda")

micim.full %>%
    filter(newlabs == "Activated Mast Cells") %>%
    ggplot(aes(x = ORIEN.est, y = TCGA.est, color = sigcode, label = mlab)) +
    facet_wrap(vars(onset), nrow = 2) +
    geom_point() +
    geom_text_repel(show.legend = F) +
    geom_hline(yintercept = 0) +
    geom_vline(xintercept = 0) +
    scale_color_manual(values = c("darkgreen", "black", "orange", "blue"),
                       name = "Significant in") +
    labs(x = "ORIEN correlation", y = "TCGA correlation") +
    theme_bw() +
    theme(legend.position = "bottom")
  
  ggsave(filename = "../figures/scatterplots_mic-immune_mast-cells.png", 
         height = 10, width = 20)
    ggsave(filename = "../figures/scatterplots_mic-immune_mast-cells_labels.svg", 
         height = 10, width = 20)
      ggsave(filename = "../figures/scatterplots_mic-immune_mast-cells_in-ms.svg", 
         height = 2, width = 3.75)
```


```{r}
load("../data/prepared-figure-data/scatterplot_corrs.rda")

micim.full %>%
    filter(newlabs == "Activated Mast Cells") %>%
    ggplot(aes(x = ORIEN.est, y = TCGA.est, color = sigcode, label = mlab)) +
    facet_wrap(vars(onset), nrow = 2) +
    geom_point(show.legend = FALSE) +
    geom_text_repel(show.legend = F) +
    geom_hline(yintercept = 0) +
    geom_vline(xintercept = 0) +
    scale_color_manual(values = c("darkgreen", "black", "orange", "blue"),
                       name = "Significant in") +
    labs(x = "ORIEN correlation", y = "TCGA correlation") +
    theme_bw()
    
  ggsave(filename = "../figures/scatterplots_mic-immune_mast-cells_in-ms_no-legend.svg", 
         height = 4, width = 3.5)
```
