---
title: "Alternative immune deconvolutions"
author: "Rebecca Hoyd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(broom)
```
# Load data

```{r}
tcga.exp <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_TCGA_expressions.csv", stringsAsFactors = F)
orien.exp <- read.csv("/fs/ess/PAS1695/projects/exorien/data/aggregated-expressions.csv", stringsAsFactors = F)

clin.orien <- read.csv("../data/clinical_ORIEN_curated.csv")
clin.tcga <- read.csv("../data/clinical_TCGA_curated.csv")
```

# Format for TIMER

```{r}
tcga.form <- tcga.exp %>%
  column_to_rownames(var = "Gene.Symbol") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  mutate(sample = gsub("\\.", "-", gsub("^X", "", sample))) %>%
  filter(sample %in% clin.tcga$sample.expression) %>%
  column_to_rownames(var = "sample") %>%
  t()

write.csv(tcga.form, "/fs/scratch/PAS1695/projects/exogieo/TIMER_tcga-input.csv", row.names = T)
```

```{r}
orien.form <- orien.exp %>%
  column_to_rownames(var = "Gene.Symbol") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample") %>%
  mutate(sample = gsub("\\.genes.*", "", sample)) %>%
  filter(sample %in% clin.orien$RNASeq) %>%
  column_to_rownames(var = "sample") %>%
  t()

write.csv(orien.form, "/fs/scratch/PAS1695/projects/exogieo/TIMER_orien-input.csv", row.names = T)

orien.form.1 <- orien.form[,1:226]
orien.form.2 <- orien.form[,227:453]
write.csv(orien.form.1, "/fs/scratch/PAS1695/projects/exogieo/TIMER_orien-input-1.csv", row.names = T)
write.csv(orien.form.2, "/fs/scratch/PAS1695/projects/exogieo/TIMER_orien-input-2.csv", row.names = T)

```


# Compare results to CIBERSORT

Choose TIMER, QUANT, and EPIC correlations


```{r}
tcga.res <- read.csv("/fs/scratch/PAS1695/projects/exogieo/estimation_matrix_tcga.csv",
                     check.names = F) %>%
  column_to_rownames(var = "cell_type") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample.expression")

orien.res <- left_join(read.csv("/fs/scratch/PAS1695/projects/exogieo/estimation_matrix_orien-1.csv"),
                       read.csv("/fs/scratch/PAS1695/projects/exogieo/estimation_matrix_orien-2.csv")) %>%
  column_to_rownames(var = "cell_type") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "sample")

ciber.orien <-read.csv("/fs/ess/PAS1695/projects/exorien/data/cibersort/2022-03-16_immunecell_composition.csv", stringsAsFactors = F) %>%
  filter(sample %in% orien.res$sample) %>%
  mutate(B.cells = B.cells.naive + B.cells.memory,
         T.cells.CD4 = T.cells.CD4.naive + T.cells.CD4.memory.resting + T.cells.CD4.memory.activated,
         Macrophage = Macrophages.M0 + Macrophages.M1 + Macrophages.M2,
         NK.cells = NK.cells.resting + NK.cells.activated
  )
ciber.tcga <- read.csv("/fs/ess/PAS1695/projects/exogieo/data/drake-output/2021-02-15_tcga_immune-cell-fractions.csv", stringsAsFactors = F) %>%
  dplyr::select(sample.expression, everything())%>%
  mutate(B.cells = B.cells.naive + B.cells.memory,
         T.cells.CD4 = T.cells.CD4.naive + T.cells.CD4.memory.resting + T.cells.CD4.memory.activated,
         Macrophage = Macrophages.M0 + Macrophages.M1 + Macrophages.M2,
         NK.cells = NK.cells.resting + NK.cells.activated
  )

# unique(gsub(".*_", "", tcga.res$cell_type))
```

Define the correlation pairs

```{r}
ciber.labs <- c("B.cells", "T.cells.CD4", "T.cells.CD8", "Neutrophils", 
                "Macrophage", 
                "B.cells", "Macrophages.M1", "Macrophages.M2", 
                "Monocytes", "Neutrophils", "NK.cells",
                "T.cells.CD4", "T.cells.CD8",
                "T.cells.regulatory..Tregs.",
                "B.cells", "T.cells.CD4", "T.cells.CD8",
                "Macrophage", "NK.cells")
other.labs <- c("B cell_TIMER", "T cell CD4+_TIMER", "T cell CD8+_TIMER", "Neutrophil_TIMER",
                "Macrophage_TIMER",
                "B cell_QUANTISEQ", "Macrophage M1_QUANTISEQ", "Macrophage M2_QUANTISEQ",
                "Monocyte_QUANTISEQ", "Neutrophil_QUANTISEQ", "NK cell_QUANTISEQ",
                "T cell CD4+ (non-regulatory)_QUANTISEQ", "T cell CD8+_QUANTISEQ",
                "T cell regulatory (Tregs)_QUANTISEQ",
                "B cell_EPIC", "T cell CD4+_EPIC", "T cell CD8+_EPIC",
                "Macrophage_EPIC", "NK cell_EPIC")
```

```{r}
orien.corrin <- ciber.orien %>%
  left_join(orien.res)
tcga.corrin <- ciber.tcga %>%
  left_join(tcga.res)
corrin <- bind_rows(orien.corrin, tcga.corrin)

corrSelectedPairs <- function(dat, p1, p2){
  tmp <- cor.test(dat[[p1]], dat[[p2]], method = "spearman") %>%
    tidy()
  return(tmp)
}

immeths.cor <- lapply(1:length(ciber.labs), function(x)
  corrSelectedPairs(corrin, ciber.labs[x], other.labs[1]))

immeths.cor.df <- bind_cols(bind_rows(immeths.cor),
                            CIBERSORT = ciber.labs,
                            OTHER = other.labs) %>%
  mutate(padj = p.adjust(p.value)) %>%
  arrange(estimate)
write.csv(immeths.cor.df, "../tables/compare-deconv-results.csv", row.names = F)
```



