---
title: "Fusobacterium multivariate modeling"
author: "Rebecca Hoyd"
date: "6/30/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(glmm)
library(broom)
```

# Load data

```{r}
# fuso <- read.csv("../data/fusobacterium_clinical-groups.csv")

# pullORIENsamps <- function(){
#   coad.ra <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_RA-with-taxonomy_COAD.csv", stringsAsFactors = F) 
#   read.ra <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_RA-with-taxonomy_READ.csv", stringsAsFactors = F) 
#   exo.ra <- bind_rows(coad.ra, read.ra)
#   return(exo.ra)
# }

mics.tcga <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_TCGA_unnormalized-microbes_humanRNAfilt_w_taxonomy.csv")
mics.orien <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_unnormalized-microbes_humanRNAfilt_w_taxonomy.csv")
clin.orien <- read.csv("../data/clinical_ORIEN_curated.csv")
clin.tcga <- read.csv("../data/clinical_TCGA_curated.csv")
```

# Format

```{r}
Hs.counts <- bind_rows(mics.tcga, mics.orien) %>%
  filter(microbe == "Homo.sapiens") %>%
  select(sample, counts)
fuso.join <- bind_rows(mics.tcga, mics.orien) %>%
  filter(order == "o__Fusobacteriales") %>%
  group_by(sample) %>%
  summarise(Fusobacteriales = sum(counts)) %>%
  left_join(Hs.counts) %>%
  mutate(Fusobacteriales = Fusobacteriales/counts)
 
orien.modin <- clin.orien %>%
  select(RNASeq, agestat, Tumor.Location, MSS.Status, Tumor.Stage) %>%
  mutate(MSS.Status = ifelse(MSS.Status == "Missing", NA, MSS.Status)) %>%
  rename("sample" = "RNASeq") %>%
  left_join(fuso.join)

tcga.modin <- clin.tcga %>%
  mutate(sample = sample.microbe) %>%
  select(sample, agestat, Tumor.Location, MSS.Status, Tumor.Stage) %>%
  mutate(MSS.Status = ifelse(MSS.Status == "Missing", NA, MSS.Status)) %>%
  left_join(fuso.join)
```

# Model

```{r}
fuso.effect.orien.univ <- glm(Fusobacteriales ~ agestat,
                          data = orien.modin,
                          family = "Gamma")

fuso.effect.orien.dropstage <- glm(Fusobacteriales ~ agestat,
                          data = filter(orien.modin, Tumor.Stage != "Missing"),
                          family = "Gamma")

fuso.effect.orien.stage <- glm(Fusobacteriales ~ agestat + 
                           # Tumor.Location,
                           Tumor.Stage,
                          data = orien.modin,
                          family = "Gamma")

fuso.effect.orien.loc <- glm(Fusobacteriales ~ agestat + 
                           Tumor.Location,
                           # PathGroupStage,
                          data = orien.modin,
                          family = "Gamma")

# fuso.effect.orien <- glm(Fusobacteriales ~ agestat + 
#                            Tumor.Location +
#                            PathGroupStage,
#                           data = orien.modin,
#                           family = "Gamma")

fuso.effect.tcga.univ <- glm(Fusobacteriales ~ agestat,
                          data = tcga.modin,
                          family = "Gamma")
fuso.effect.tcga <- glm(Fusobacteriales ~ agestat + Tumor.Location + Tumor.Stage,
                          data = tcga.modin,
                          family = "Gamma")
```

## ORIEN models

```{r}
summary(fuso.effect.orien.univ)

summary(fuso.effect.orien.dropstage)
```

```{r}
summary(fuso.effect.orien.loc)

summary(fuso.effect.orien.stage)
```

```{r}
anova(fuso.effect.orien.univ, fuso.effect.orien.loc, test = "LRT")
anova(fuso.effect.orien.univ, fuso.effect.orien.stage, test = "LRT")

```

## TCGA models

```{r}
summary(fuso.effect.tcga.univ)
```

```{r}
summary(fuso.effect.tcga)
```


