---
title: "generate ORIEN processed dataset"
author: "Rebecca Hoyd"
date: "1/19/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```
# Load data

```{r}
methyl.samps <- read.table("../data/key_all-sample-ids-with-pnt-barcodes-msi_pole_pold_status_358.txt", sep = "\t", header = T)

coad.mic <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_TCGA_RA-with-taxonomy_COAD.csv")
read.mic <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_TCGA_RA-with-taxonomy_READ.csv")

coad.exp <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_TCGA_expressions_normalized_COAD.csv")
read.exp <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_TCGA_expressions_normalized_READ.csv")
```

# Combine and filter

```{r}
mics <- bind_rows(coad.mic, read.mic) %>%
  filter(sample %in% methyl.samps$sample.microbe)

exp <- bind_rows(coad.exp, read.exp) %>%
  filter(sample %in% methyl.samps$sample.expression)
```

# Save

```{r}
write.csv(mics, "/fs/ess/PAS1695/projects/exogieo/data/ORIEN-processing/2022-03-16_RA-with-taxonomy.csv", row.names = F)
write.csv(exp, "/fs/ess/PAS1695/projects/exogieo/data/ORIEN-processing/2022-03-16_normalized-expressions.csv", row.names = F)
```

# Unnormalized versions

```{r}
filtmics <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_TCGA_unnormalized-microbes_humanRNAfilt_w_taxonomy.csv")
rawexp <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_TCGA_expressions.csv")

filtmics.gieo <- filtmics %>%
  filter(sample %in% methyl.samps$sample.microbe)

rawexp.gieo <- rawexp %>%
  pivot_longer(-Gene.Symbol, names_to = "sample", values_to = "count") %>%
  mutate(sample = gsub("\\.", "-", gsub("^X", "", sample))) %>%
  filter(sample %in% methyl.samps$sample.expression) %>%
  pivot_wider(names_from = "Gene.Symbol", values_from = "count")


write.csv(filtmics.gieo, "/fs/ess/PAS1695/projects/exogieo/data/ORIEN-processing/2022-03-16_unnorm-mics_filt.csv", row.names = F)
write.csv(rawexp.gieo, "/fs/ess/PAS1695/projects/exogieo/data/ORIEN-processing/2022-03-16_unnorm-expressions.csv", row.names = F)
```

