---
title: "gather fusobacterium groups"
author: "Rebecca Hoyd"
date: "6/6/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# Load objects

```{r}
orien.ra <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_unnormalized-microbes_humanRNAfilt_w_taxonomy.csv", stringsAsFactors = F)
# coad.ra <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_RA-with-taxonomy_COAD.csv", stringsAsFactors = F) 
# read.ra <- read.csv("/fs/ess/PAS1695/projects/exorien/data/drake-output/2022-03-16/2022-03-16_RA-with-taxonomy_READ.csv", stringsAsFactors = F) 

tcga.ra <- read.csv("/fs/ess/PAS1695/projects/exogieo/data/ORIEN-processing/2022-03-16_unnorm-mics_filt.csv", stringsAsFactors = F)

clin.orien <- read.csv("../data/clinical_ORIEN_curated.csv")
clin.tcga <- read.csv("../data/clinical_TCGA_curated.csv")
```

# Format

```{r pull RA}
# orien.ra <- bind_rows(coad.ra, read.ra) %>%
#   filter(microbe == "Fusobacterium.nucleatum") %>%
#   select(sample, exo.ra) %>%
#   rename("F.nucleatumRA" = "exo.ra") %>%
#   mutate(dataset = "ORIEN")
# tcga.fuso <- tcga.ra %>%
#   filter(microbe == "Fusobacterium.nucleatum") %>%
#   select(sample, exo.ra) %>%
#   rename("F.nucleatumRA" = "exo.ra") %>%
#   mutate(dataset = "TCGA")

# Retrieve all Fusobacteria
orien.ra.aF <- 
  orien.ra %>%
  filter(grepl("Fusobac", microbe)) %>%
  select(sample, microbe, counts) %>%
  filter(!grepl("virus", microbe)) %>%
  pivot_wider(names_from = "microbe", values_from = "counts") %>%
  mutate(dataset = "ORIEN")

tcga.fuso.aF <- tcga.ra %>%
  filter(grepl("Fusobac", microbe)) %>%
  select(sample, microbe, counts) %>%
  pivot_wider(names_from = "microbe", values_from = "counts") %>%
  mutate(dataset = "TCGA")

# Aggregate to genus RA
orien.fuso.gen <- orien.ra %>%
  filter(grepl("Fusobac", microbe)) %>%
  filter(!grepl("virus", microbe)) %>%
  select(sample, microbe, counts) %>%
  group_by(sample) %>%
  summarize(Fusobacterium = sum(counts))

tcga.fuso.gen <- tcga.ra %>%
  filter(grepl("Fusobac", microbe)) %>%
  filter(!grepl("virus", microbe)) %>%
  select(sample, microbe, counts) %>%
  group_by(sample) %>%
  summarize(Fusobacterium = sum(counts))
```

```{r pull clin vars}
clin.tcga.selected <- clin.tcga %>%
  select(sample.microbe, age_at_diagnosis, ajcc_pathologic_stage) %>%
  mutate(stage = str_remove(ajcc_pathologic_stage, "Stage "),
         stage = str_remove(stage, "A"),
         stage = str_remove(stage, "B"),
         stage = str_remove(stage, "C"),
         Onset = ifelse((age_at_diagnosis/365.25) < 50, "EO", "LO"),
         sample = sample.microbe) %>%
  select(sample, stage, Onset)
clin.orien.selected <- clin.orien %>%
  select(RNASeq, PathGroupStage, AgeAtDiagnosis) %>%
  mutate(sample = RNASeq,
         stage = ifelse(grepl("Unknown", PathGroupStage), NA, PathGroupStage),
         stage = ifelse(grepl("No", stage), NA, stage),
         stage = str_remove(stage, "A"),
         stage = str_remove(stage, "B"),
         stage = str_remove(stage, "C"),
         Onset = ifelse(AgeAtDiagnosis < 50, "EO", "LO")) %>%
  select(sample, stage, Onset)
```

```{r combine}
orien.all <- 
  clin.orien %>%
  dplyr::rename("sample" = "RNASeq") %>%
  select(sample, Tumor.Stage, agestat) %>%
  inner_join(orien.ra.aF) %>%
  inner_join(orien.fuso.gen)

tcga.all <- 
  clin.tcga %>%
  dplyr::rename("sample" = "sample.microbe") %>%
  select(sample, Tumor.Stage, agestat) %>%
  inner_join(tcga.fuso.aF) %>%
  inner_join(tcga.fuso.gen)

full.datset <- bind_rows(orien.all, tcga.all) %>%
  select(-contains("virus"))
```

# Save

```{r}
write.csv(full.datset, "../data/fusobacterium_clinical-groups.csv", row.names = F)
```

# Fusobacterium boxplots by category

```{r}
fuso <- read_csv("../data/fusobacterium_clinical-groups.csv")

head(fuso)
```

```{r}
fuso %>%
  ggplot(aes(x = agestat, y = log(Fusobacterium))) +
  geom_violin(aes(fill = agestat)) +
  geom_boxplot(width = 0.2) +
  geom_jitter(width = 0.2) +
  facet_wrap(~dataset) +
  scale_fill_brewer(palette = "Set1") +
  theme_bw()

ggsave("../figures/fusobacterium_boxplot_orien-tcga.png",
       height = 2, width = 5)
```

